const lang: any = {
  CN: {
    setting: '设置',
    fullscreen: '进入全屏',
    exitscreen: '退出全屏',
    webscreen: '网页全屏',
    exitweb: '退出全屏',
    intotheater: '剧场模式',
    picture: '画中画',
    playMode: '播放方式',
    playRate: '播放速度',
    playSetting: '其他设置',
    noLight: '关灯模式',
    default: '默认',
    autoLoop: '自动循环',
    endStop: '播完暂停',
    showSubtitle: '字幕设置',
    subtitle: '显示字幕',
    nosubtitle: '隐藏字幕',
    subsize: '字幕大小',
    subsize1: '极小',
    subsize2: '小',
    subsize3: '正常',
    subsize4: '大',
    subsize5: '超大',
    subcolor: '字幕颜色',
    submargin: '字幕高度',
    submargin1: '极低',
    submargin2: '低',
    submargin3: '正常',
    submargin4: '高',
    submargin5: '超高',
  },
  EN: {},
};

export default lang;
